### ISSUE TITLE
Contributions?

### ISSUE THREAD

**Issue by mrjbq7** [kusumotonorio/factlog#1]
Would you like contributions to this?  I could make pull requests?

Some suggestions:

1) Make this a "vocab-root", so move ``logica.factor`` into a ``logica`` folder.  You can leave the ``README`` in the root.

2) Move the "tests" like ``logica/test/hanoi`` to ``logica/examples/hanoi/hanoi.factor`` and then add a ``logica/examples/hanoi/hanoi-tests.factor`` that has test cases that can be run to ensure the code works.

3) Make a ``logica/logica-tests.factor`` with a few tests also.

4) I cleaned up some of the code, for example ``dereference`` and ``split-body`` and ``collect-logic-vars``, here's a git diff... I could make a PR if you're interested and keep making some improvements....

```diff
diff --git a/logica.factor b/logica.factor
index b8e444c..fad53e9 100644
--- a/logica.factor
+++ b/logica.factor
@@ -1,10 +1,11 @@
 ! Copyright (C) 2019 KUSUMOTO Norio.
 ! See http://factorcode.org/license.txt for BSD license.
-USING: accessors arrays kernel locals sequences classes.parser
-continuations words.symbol namespaces lexer parser words sets
-assocs combinators quotations math hashtables lists classes
-classes.tuple prettyprint prettyprint.custom formatting
-compiler.units sequences.generalizations io strings ;
+USING: accessors arrays assocs classes classes.parser
+classes.tuple combinators compiler.units continuations
+formatting hashtables io kernel lexer lists locals math
+namespaces parser prettyprint prettyprint.custom quotations
+sequences sequences.deep sets splitting strings words
+words.symbol ;
 
 IN: logica
 
@@ -21,8 +22,8 @@ TUPLE: logic-pred name defs ;
 
 : <pred> ( name -- pred )
     logic-pred new
-    swap >>name
-    { } clone >>defs ;
+        swap >>name
+        { } clone >>defs ;
 
 :: parse-list ( seq -- list )
     seq [ || = ] find drop :> d-pos
@@ -100,25 +101,20 @@ TUPLE: logic-env table ;
 
 : env-clear ( env -- ) table>> clear-assoc ; inline
 
-:: dereference ( term! env! -- term' env' )
-    t :> loop?!
-    [ term logic-var? loop? and ] [
-        term env env-get :> pair!
-        pair [ pair first2 env! term! ] [ f loop?! ] if
-    ] while
-    term env ;
+: dereference ( term env -- term' env' )
+    [ 2dup env-get [ 2nip first2 t ] [ f ] if* ] loop ;
 
 SYMBOL: L{
 
 M: cons-state pprint-delims drop \ L{ \ } ;
 
 M:: cons-state >pprint-sequence ( x -- seq ) 
-   x [ car ] [ cdr ] bi :> ( x-car x-cdr )
-   x-cdr nil? [ x-car 1array ] [
+    x [ car ] [ cdr ] bi :> ( x-car x-cdr )
+    x-cdr nil? [ x-car 1array ] [
         x-cdr cons-state? [
             x-car 1array x-cdr >pprint-sequence append
         ] [ x-car || x-cdr 3array ] if
-   ] if ;
+    ] if ;
 
 M: cons-state pprint* pprint-object ;
 
@@ -162,7 +158,7 @@ C: <cut> cut-info
     dup cut?>> [ 2drop ] [ cut?<< ] if ; inline
 
 DEFER: unify*
-    
+
 :: (unify*) ( x! x-env! y! y-env! trail tmp-env -- success? )
     f :> ret-value!  f :> ret?! f :> ret2?!
     t :> loop?!
@@ -185,11 +181,11 @@ DEFER: unify*
             ] }
           { [ y logic-var? ] [
                 x y x! y!  x-env y-env x-env! y-env!
-            ] }                 
+            ] }
           [ f loop?! ]
         } cond
     ] while
-    
+
     ret? [
         t ret-value!
         x y [ logic-goal? ] both? [
@@ -199,9 +195,9 @@ DEFER: unify*
                 f ret-value! t ret2?!
             ] if
         ] when
-        ret2? [           
-            {                
-                { [ x y [ tuple? ] both? ] [                      
+        ret2? [
+            {
+                { [ x y [ tuple? ] both? ] [
                       x y [ class-of ] same? [
                           x y [ tuple-slots ] bi@ :> ( x-slots y-slots )
                           0 :> i!  x-slots length 1 - :> stop-i  t :> loop?!
@@ -214,8 +210,8 @@ DEFER: unify*
                               ] unless
                               i 1 + i!
                           ] while
-                      ] [ f ret-value! ] if     
-                  ] }                
+                      ] [ f ret-value! ] if
+                  ] }
                 { [ x y [ sequence? ] both? ] [
                       x y [ class-of ] same? x y [ length ] same? and [
                           0 :> i!  x length 1 - :> stop-i  t :> loop?!
@@ -228,8 +224,8 @@ DEFER: unify*
                               i 1 + i!
                           ] while
                       ] [ f ret-value! ] if
-                  ] }              
-                [  x y = ret-value! ]
+                  ] }
+                [ x y = ret-value! ]
             } cond
         ] unless
     ] unless
@@ -252,17 +248,16 @@ DEFER: unify*
     ] when
     success? ;
 
-:: resolve-body ( body env cut quot: ( -- ) -- )   
+:: resolve-body ( body env cut quot: ( -- ) -- )
     body empty? [
         quot call( -- )
     ] [
-        body first :> first-goal!
-        body rest  :> rest-goals!
+        body unclip :> ( rest-goals! first-goal! )
         first-goal !! = [           ! cut
             rest-goals env cut [ quot call( -- ) ] resolve-body
             t cut set-info
         ] [
-            first-goal callable? [ 
+            first-goal callable? [
                 first-goal call( -- goal ) first-goal! 
             ] when
             *trace?* get-global [
@@ -271,13 +266,13 @@ DEFER: unify*
                 [ args>> [ "%u " printf ] each "}\n" printf ] bi
             ] when
             <env> :> d-env!
-            f <cut> :> d-cut!   
+            f <cut> :> d-cut!
             first-goal pred>> defs>> [
-                [ first ] [ second ] bi :> ( d-head d-body )
+                first2 :> ( d-head d-body )
                 d-cut cut? cut cut? or [ t ] [
                     V{ } clone :> trail
                     first-goal env d-head d-env trail d-env unify* [
-                        d-body callable? [                  
+                        d-body callable? [
                             d-env trail <callback-env> d-body call( cb-env -- ? ) [
                                 rest-goals env cut [ quot call( -- ) ] resolve-body
                             ] when
@@ -296,17 +291,8 @@ DEFER: unify*
         ] if
     ] if ;
 
-:: split-body ( body -- bodies )
-    V{ } clone :> bodies
-    V{ } clone :> goals!
-    body [
-        dup vel = [
-            drop goals >array bodies push
-            V{ } clone goals!
-        ] [ goals push ] if
-    ] each
-    goals empty? [ goals >array bodies push ] unless
-    bodies >array ;
+: split-body ( body -- bodies )
+    { vel } split [ >array ] map ;
 
 SYMBOL: *anonymouse-var-no*
 
@@ -330,21 +316,8 @@ SYMBOL: *anonymouse-var-no*
         [ ]
     } cond ;
 
-:: collect-logic-vars ( seq -- vars-array )
-    V{ } clone :> vars
-    seq [
-        { { [ dup logic-var? ] [
-                dup vars member? [ drop ] [ vars push ] if 
-            ] }
-          { [ dup sequence? ] [
-                collect-logic-vars [
-                    dup vars member? [ drop ] [ vars push ] if
-                ] each
-            ] }
-          [ drop ]
-        } cond
-    ] each
-    vars >array ;
+: collect-logic-vars ( seq -- vars-array )
+    [ logic-var? ] deep-filter members ;
 
 :: (resolve) ( goal-def/defs quot: ( env -- ) -- )
     goal-def/defs replace-'__' normalize [
@@ -358,15 +331,16 @@ SYMBOL: dummy-item
 :: non-goal ( goal -- non-goal )
     "failo" <pred> :> f-pred
     f-pred { } clone logic-goal boa :> f-goal
-    f-goal [ drop f ] 2array 1array f-pred defs<<
+    { { f-goal [ drop f ] } } f-pred defs<<
     "trueo" <pred> :> t-pred
     t-pred { } clone logic-goal boa :> t-goal
-    t-goal [ drop t ] 2array 1array t-pred defs<<
+    { { t-goal [ drop t ] } } t-pred defs<<
     goal pred>> name>> "non-%s_" sprintf <pred> :> non-pred
     non-pred goal args>> clone logic-goal boa :> non-goal
-    non-goal goal !! f-goal 3array 2array
-    non-goal t-goal 1array 2array
-    2array non-pred defs<<  ! non-P_ { P !! { failo } vel { trueo } } si  
+    {
+        { non-goal { goal !! f-goal } }
+        { non-goal { t-goal } }
+    } non-pred defs<<  ! non-P_ { P !! { failo } vel { trueo } } si
     non-goal ;
 
 SYMBOLS: at-the-beginning and at-the-end ;
@@ -377,7 +351,7 @@ SYMBOLS: at-the-beginning and at-the-end ;
     body replace-'__' normalize split-body  ! disjunction
     dup empty? [
         head-goal swap 2array
-        head-goal pred>> [ swap 1array append ] change-defs drop
+        head-goal pred>> [ swap suffix ] change-defs drop
     ] [
         f :> non?!
         [
@@ -385,7 +359,7 @@ SYMBOLS: at-the-beginning and at-the-end ;
                 {
                     { [ dup non = ] [ drop dummy-item t non?! ] }
                     { [ dup array? ] [
-                          [ first ] [ rest ] bi <goal> non? [ non-goal ] when 
+                          [ first ] [ rest ] bi <goal> non? [ non-goal ] when
                           f non?!
                       ] }
                     { [ dup callable? ] [
@@ -397,19 +371,19 @@ SYMBOLS: at-the-beginning and at-the-end ;
                           t/f [ "trueo" ] [ "failo" ] if <pred> :> t/f-pred
                           { } clone :> args
                           t/f-pred args logic-goal boa :> t/f-goal
-                          t/f-goal [ drop t/f ] 2array 1array t/f-pred defs<<
+                          { { t/f-goal [ drop t/f ] } } t/f-pred defs<<
                           t/f-goal
                           f non?!
                       ] }
-                    { [ dup !! = ] [ f non?! ] }  ! as '!!'     
+                    { [ dup !! = ] [ f non?! ] }  ! as '!!'
                     [ drop dummy-item f non?! ]
                 } cond
             ] map dummy-item swap remove :> body-goals
-            head-goal body-goals 2array
+            { head-goal body-goals }
             head-goal pred>> [
                 swap 1array pos at-the-beginning = [ swap ] when append
             ] change-defs drop
-        ] each    
+        ] each
     ] if ;
 
 PRIVATE>
@@ -420,8 +394,9 @@ PRIVATE>
 
 :: voca ( head quot: ( callback-env -- ? ) -- )
     head [ first ] [ rest ] bi <goal> :> head-goal
-    head-goal quot 2array head-goal pred>>
-    [ swap 1array append ] change-defs drop ;
+    head-goal pred>> [
+        { head-goal quot } suffix
+    ] change-defs drop ;
 
 :: unify ( cb-env x y -- success? )
     cb-env env>> :> env
@@ -429,39 +404,49 @@ PRIVATE>
 
 :: is ( quot: ( env -- value ) dist -- goal )
     quot collect-logic-vars
-    dup dist swap member? [ dist 1array append ] unless :> args 
+    dup dist swap member? [ dist suffix ] unless :> args
     quot dist "[ %u %s is ]" sprintf <pred> :> is-pred
     is-pred args logic-goal boa :> is-goal
-    is-goal [| env | env dist env quot call( env -- value ) unify ] 2array
-    1array is-pred defs<<
+    {
+        {
+            is-goal
+            [| env | env dist env quot call( env -- value ) unify ]
+        }
+    } is-pred defs<<
     is-goal ;

 :: =:= ( quot1: ( env -- value ) quot2: ( env -- value )  -- goal )
     quot1 quot2 [ collect-logic-vars ] bi@ union :> args
     quot1 quot2 "[ %u %u =:= ]" sprintf <pred> :> =:=-pred
     =:=-pred args logic-goal boa :> =:=-goal
-    =:=-goal [| env |
-              env quot1 call( env -- value )
-              env quot2 call( env -- value )
-              2dup [ number? ] both? [ = ] [ 2drop f ] if ]
-    2array
-    1array =:=-pred defs<<
+    {
+        {
+            =:=-goal
+            [| env |
+                env quot1 call( env -- value )
+                env quot2 call( env -- value )
+                2dup [ number? ] both? [ = ] [ 2drop f ] if
+            ]
+        }
+    } =:=-pred defs<<
     =:=-goal ;
 
 :: =\= ( quot1: ( env -- value ) quot2: ( env -- value )  -- goal )
     quot1 quot2 [ collect-logic-vars ] bi@ union :> args
     quot1 quot2 "[ %u %u =\\= ]" sprintf <pred> :> =\=-pred
     =\=-pred args logic-goal boa :> =\=-goal
-    =\=-goal [| env |    
-              env quot1 call( env -- value )
-              env quot2 call( env -- value )
-              2dup [ number? ] both? [ = not ] [ 2drop f ] if ]
-    2array
-    1array =\=-pred defs<<
+    {
+        {
+            =\=-goal
+            [| env |
+                env quot1 call( env -- value )
+                env quot2 call( env -- value )
+                2dup [ number? ] both? [ = not ] [ 2drop f ] if
+            ]
+        }
+    } =\=-pred defs<<
     =\=-goal ;
 
-M: array >list sequence>list ;
-
 : resolve ( goal-def/defs quot: ( env -- ) -- ) (resolve) ;
 
 : resolve* ( goal-def/defs -- ) [ drop ] resolve ;
@@ -474,30 +459,30 @@ M: array >list sequence>list ;
     [
         goal-def/defs normalize
         [| env |
-         V{ } clone :> bindings
-         env table>>
-         keys [| key |
-               key get NORMAL-LOGIC-VAR? [
-                   key dup env at 2array bindings push
-                   trace? [ key "%u: " printf key env at pprint nl ] when
-               ] when
-              ] each
-         bindings >hashtable bindings-seq push
-         t success?!
-         n/f [
-             count 1 + count!
-             count n/f >= [ return ] when
-         ] when
+            V{ } clone :> bindings
+            env table>>
+            keys [| key |
+                key get NORMAL-LOGIC-VAR? [
+                    key dup env at 2array bindings push
+                    trace? [ key "%u: " printf key env at pprint nl ] when
+                ] when
+            ] each
+            bindings >hashtable bindings-seq push
+            t success?!
+            n/f [
+                count 1 + count!
+                count n/f >= [ return ] when
+            ] when
         ] (resolve)
     ] with-return
-    bindings-seq >array    
+    bindings-seq >array
     {
         { [ dup empty? ] [ drop success? ] }
         { [ dup first keys [ get NORMAL-LOGIC-VAR? ] filter empty? ] [
               drop success?
           ] }
         [ ]
-        } cond ;
+    } cond ;
 
 : query ( goal-def/defs -- bindings-array/success? ) f query-n ;
```

**Comment by mrjbq7** [comment]
I poked at it a little more and I pushed the ``L{`` syntax into the main repository, and cleaned up a few more things... just let me know if you want a PR, etc.

**Comment by kusumotonorio** [comment]
I just noticed this comment. First of all, let me thank you for taking logica very seriously!  I welcome your, and others', suggestions.

Although logica is still incomplete and would not normally be able to stand up for publication, I thought it would be better to open up the code to get another factor programmer's opinion. Now I feel that the idea was good.

I hope for your PR. Your code will be very useful for my Factor study. I will read it and learn.

The original author I referred to probably wrote such code just to satisfy intellectual curiosity. My hope is that logoca will not just be able to solve the same puzzles as Prolog, but that it will be able to add sophisticated functionality to programs written in factor.

I expect to have to add something that isn't in the original, but I have to think about what it is and it is possible or not.

**Comment by kusumotonorio** [comment]
As I wrote elsewhere, there is a problem with my L{ syntax. It does not handle dotted pair notation correctly.
Other people may not want dotted pair notation at the moment, but I would eventually need it because the chain constructed by cons-state can be something other than a linear list.
```
1 2 cons 3 4 cons cons .
```

**Comment by mrjbq7** [comment]
Wouldn’t this be a tree-type structure without dotted syntax?  Nested cons?

L{ 1 L{ 2 3 } L{ 4 5 } } 

Or did you mean something else?

**Comment by kusumotonorio** [comment]
I think `1 2 cons 3 4 cons cons` should be `L{ L{ 1 || 2 } || L{ 3 || 4 } }`. 

But, Factor loaded logica answers `L{ L{ 1 || 2 } 3 || 4 }`.

**Comment by mrjbq7** [comment]
Why do you want the || notation? I know that’s classical lisp maybe but unnecessary?

**Comment by kusumotonorio** [comment]
I think `.` is really desirable, but `.` is a major word, and using it is not enough for the user to say `USE: logica`. Prolog uses `|`, so I decided to make it similar.
`|` is also used in Factor code. I wasn't sure, but for fear of affecting syntax macros, I didn't just use `|`.

**Comment by kusumotonorio** [comment]
The print form of cons-state should be able to represent situations where the cdr of cons-state points to something that is not a linear list. Also, because Prolog programs require a syntax that points to the tail, we need some notation equivalent to dotted pair notation.

**Comment by kusumotonorio** [comment]
So my point is that I don't care about `||`, but we need some expression indicating that some cons-state cdr points to something other than a linear list. If factor has such a standard, I'll use it.

**Comment by kusumotonorio** [comment]
By the way, I think your indentation is more readable than mine.
My indentation is the result of emacs, which includes fuel, almost coercing it. Which editor do you use? Is it possible to adjust the indentation of fuel to a better one?

**Comment by kusumotonorio** [comment]
```
-:: dereference ( term! env! -- term' env' )
-    t :> loop?!
-    [ term logic-var? loop? and ] [
-        term env env-get :> pair!
-        pair [ pair first2 env! term! ] [ f loop?! ] if
-    ] while
-    term env ;
+: dereference ( term env -- term' env' )
+    [ 2dup env-get [ 2nip first2 t ] [ f ] if* ] loop ;
```
`dereference` must stop the loop when `term` is not `logic-var`.  Is it the same in the end?

**Comment by mrjbq7** [comment]
Yes, I believe so. The loop goes until it sees an `f` which will be when env-get fails to find a pair, similar to the above code.

**Comment by kusumotonorio** [comment]
Certainly, when the code read with a key which is not a logic variable, the hash table will return `f`. So those codes seem to be equivalent.

I think the reason why the person who wrote the Prolog processing engine in Ruby tested term as a variable here. It might be to reduce the cost of a hash table one time...

**Comment by kusumotonorio** [comment]
Hmm. It seems my understanding is wrong.
logica seems to be right now.
```
gosh> (cons (cons 1 2) (cons 3 4) )
((1 . 2) 3 . 4)
gosh> '( (1 . 2) . (3 . 4))
((1 . 2) 3 . 4)
gosh>
```

**Comment by kusumotonorio** [comment]
```factor
IN: scratchpad L{ L{ 1 . 2 } . L{ 3 . 4 } }

--- Data stack:
L{ ~cons-state~ 3 . 4 }
IN: scratchpad .
L{ L{ 1 . 2 } 3 . 4 }
```
I modified it to use `.` on a trial basis again. This one is better.
It doesn't matter when we use it in the listener, but when an user  actually write a program, he will be forced to write `USE: prettyprint`, or if we declare `.` in logica, the Factor will ask him which to use.

Can Factor handle this situation well?
If that is possible, I would prefer that such a cons-state prityprint be included in the standard.

**Comment by mrjbq7** [comment]
I don't understand that last example.  Why is it like this:

```
IN: scratchpad L{ L{ 1 . 2 } . L{ 3 . 4 } } .
L{ L{ 1 . 2 } 3 . 4 }
```

And not like this:

```
IN: scratchpad L{ L{ 1 . 2 } . L{ 3 . 4 } } .
L{ L{ 1 . 2 } . L{ 3 . 4 } }
```

Or even this:

```
IN: scratchpad L{ L{ 1 . 2 } . L{ 3 . 4 } } .
L{ L{ 1 . 2 } . 3 . 4 }
```

**Comment by kusumotonorio** [comment]
The list can be represented by the following figure, where "car" is the down branch and "cdr" is the right branch.

`L{ 1 2 3 4 }` is :
```
+--+--+--+-- +nil+
|  |  |  |
1  2  3  4
```
`L{ L{ 1 . 2 } . L{ 3 . 4 } }` is :
```
+--+--4
|  |
|  3
+--2
|
1
```
`L{ L{ 1 . 2 } 3 . 4 }` is also :
```
+--+--4
|  |
|  3
+--2
|
1
```
`L{ L{ 1 . 2 } . 3 . 4 }` cannot be realized. You cannot use dots for three elements. The dots on the left are "car" and the dots on the right are "cdr". There are only two elements.

**Comment by mrjbq7** [comment]
I'm familiar with the general ``( car . cdr )`` form, but find it confusing whether the second item represents the "rest of the list", or "just a last item".

https://stackoverflow.com/questions/20216711/dot-notation-in-scheme

The example ``L{ L{ 1 . 2 } 3 . 4 } `` seems to violate the "car dot cdr" rule, so I'm trying to understand it.

I've also generally seen most people print lists without dots because this:

```
( 1 . ( 2 . ( 3 . ( 4 . ( 5 . ( ) ) ) ) )
```

Is a lot uglier than:

```
( 1 2 3 4 5 )
```

With implicit dots.

**Comment by kusumotonorio** [comment]
When cdr points to `cons-state`, it is considered "rest of the list" and no dots are printed. Also, when it is `+nil+`, it is determined that the list is over and no dot is printed. (`+nil+` can be said to be an empty list.)
On the other hand, when what cdr points to is not them, it is "just a last item", so a dot is used.

**Comment by kusumotonorio** [comment]
> The example L{ L{ 1 . 2 } 3 . 4 } seems to violate the "car dot cdr" rule, so I'm trying to understand it.


`L{ L{ 1 . 2 } 3 . 4 }` can be thought of as the first element `"first-item"` in `L{ "first-item" 3 . 4 }` replaced by  `L{ 1 . 2 }`. In other words, it is an expression that follows the rules.

**Comment by kusumotonorio** [comment]
> The example L{ L{ 1 . 2 } 3 . 4 } seems to violate the "car dot cdr" rule, so I'm trying to understand it.

`L{ L{ 1 . 2 } 3 . 4 }` can be thought of as the first element `"first-item"` in `L{ "first-item" 3 . 4 }` replaced by `L{ 1 . 2 }`. So, it is an expression that follows the rules.

```
  +----+--4
  |    |
  |    3
"first-item"
```

**Comment by kusumotonorio** [comment]
I add this to explain the dotted pair notation that I want to realize.
This is an interaction with a Scheme processing system.
```
gosh> '(1 2 3 . 4)
(1 2 3 . 4)
gosh> '(1 2 . (3 . 4))
(1 2 3 . 4)
gosh> '(1 . (2 . (3 . 4)))
(1 2 3 . 4)
```
```
+--+--+--4
|  |  |
1  2  3
```

**Comment by kusumotonorio** [comment]
> The example L{ L{ 1 . 2 } 3 . 4 } seems to violate the "car dot cdr" rule, so I'm trying to understand it.

So, I think it's better to think that a dot is written between elements of a list and the rest of the list rather than being written between car and cdr. 
If the rule is applied to a single `cons-state` list, a dot is written between car and cdr, `L{ CAR . CDR }` .

**Comment by mrjbq7** [comment]
I'm sorry if it's obvious, but is ``L{ L{ 1 . 2 } 3 . 4 }`` the same as:

```
cons ( cons ( 1 , 2 ) cons ( 3 , 4 ) )
```

Meaning the ``car`` is ``L{ 1 2 }`` and the ``cdr`` is ``L{ 3 4 }``?

**Comment by kusumotonorio** [comment]
```
gosh> (cons (cons 1 2) (cons 3 4))
((1 . 2) 3 . 4)
```
```
(cs3)--(cs2)--4
  |      |
  |      3
(cs1)--2
  |
  1
```
The car for CS1 is `1` and the cdr for CS1 is `2`.
The car on CS2 is `3` and the cdr on CS2 is `4`.
The car for CS3 is `L{ 1 . 2 }` and the cdr for CS3 is `L{ 3 . 4 }`.

Either `L{ L{ 1 . 2 } . L{ 3 . 4 } }` or `L{ L{ 1 . 2 } 3 . 4 }` is correct, but programs that print dotted pairs usually use an algorithm such as `L{ L{ 1 . 2 } 3 . 4 }`. Because such an algorithm prints 
```
+--+--+--+-- +nil+
|  |  |  |
1  2  3  4
``` 
as `L{ 1 2 3 4 }`.

**Comment by kusumotonorio** [comment]
In addition, `L{ 1 2 }` has the structure:
```
+--+-- +nil+
|  |
1  2
```
 
If `L{ 1 2 }` is printed, it is a mistake because such a structure is not in the structure created by` (cons (cons 1 2) (cons 3 4)) `.

**Comment by kusumotonorio** [comment]
With Factor:
```
1 2 cons 3 4 cons cons
```

**Comment by mrjbq7** [comment]
Aha! I get it!!

Thanks!

**Comment by kusumotonorio** [comment]
I'm glad to hear that!

**Comment by kusumotonorio** [comment]
I think that now you can see what I wanted to say in the discussion of literal expressions in the lazy lists.
The reason the dots don't appear in the representation of a list is that the list can be expressed fortunately without using dots.
I think L{ syntax macros and pprint should support dot pair notation. Otherwise,  we and Factor cannot represent the composite structure that `cons-state`s make up.

**Comment by kusumotonorio** [comment]
The above dot notation for Factor was fictional or temporary and experimental, but I've changed the actual Factor list representation in factlog from Prolog-like to Lisp-like. 

We can actually do the following:
```Factor
Press F1 at any time for help.
Factor 0.99 x86.32 (1914, heads/master-0ea9f8935d, Sep 11 2019 09:24:35)
[Microsoft Visual C++ 190023506] on windows

IN: scratchpad USE: factlog
IN: scratchpad L( 1 . L( 2 . L( 3 . L( 4 . L( 5 . L( ) ) ) ) ) ) .
L( 1 2 3 4 5 )
IN: scratchpad 1 2 cons 3 4 cons cons .
L( L( 1 . 2 ) 3 . 4 )
IN: scratchpad L( L( 1 . 2 ) . L( 3 . 4 ) ) .
L( L( 1 . 2 ) 3 . 4 )
IN: scratchpad 
```

**Comment by mrjbq7** [comment]
Cool!!

**Comment by kusumotonorio** [comment]
As mentioned earlier, I believe that the literal representation of lists in `lists` vocab should support such dotted pair notation. 
After examining the behavior of the list in factlog, I would like to suggest it as the  literal representation of the standard list.

**Comment by mrjbq7** [comment]
I'd be happy to look it over later, unless you get to a PR before I do.

Would you also like to contribute the whole factlog someday to the main Factor repository also?

**Comment by kusumotonorio** [comment]
> Would you also like to contribute the whole factlog someday to the main Factor repository also?

Yes. For that I have to finish factlog-docs.factor.
And if the Factor standard list supports dot pair notation, I would stop using factlog's own list and rewrite it to use the standard one.

**Comment by kusumotonorio** [comment]
I have written `factlog-docs.factor` to the bare minimum.
If I can see that the modified `faclog.factor` works fine, I'm ready for PR.

**Comment by kusumotonorio** [comment]
Ok, I think I could change `factlog-docs.factor` to pass `help-lint`.

**Comment by kusumotonorio** [comment]
I would like `+nil+` to print as `L{ }`.
```Factor
IN: scratchpad L{ } .
+nil+
```
We can do this by adding the following statement to `prettyprint.backend`.

```Factor
M: +nil+ pprint* drop "L{ }" text ;
```

**Comment by mrjbq7** [comment]
Fixed in https://github.com/factor/factor/commit/6599869f738a3ba04ecad45b1e35e1bacf2d6730.

**Comment by kusumotonorio** [comment]
Thanks!

**Comment by kusumotonorio** [comment]
factlog was merged into Factor.
